options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - export IMAGE_NAME=quay.io/softonic/tva-voting:$BITBUCKET_COMMIT
          - docker build -t $IMAGE_NAME .
          - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD quay.io
          - docker push $IMAGE_NAME
