options:
  docker: true
image: google/cloud-sdk
clone:
  depth: 1

pipelines:
  default:
    - step:
        script:

          #---------------------
          # Build tag and push:
          #---------------------

          - export IMAGE_NAME=quay.io/softonic/tva-voting
          - docker build -t ${IMAGE_NAME}:${BITBUCKET_COMMIT::6} .
          - docker tag ${IMAGE_NAME}:${BITBUCKET_COMMIT::6} ${IMAGE_NAME}:latest
          - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} quay.io
          - docker push ${IMAGE_NAME}

          #---------------------------
          # Activate service account:
          #---------------------------

          - gcloud init
          - echo ${GCLOUD_SVCACCOUNT_KEY} | base64 --decode --ignore-garbage > gcloud-svcaccount-key.json
          - gcloud auth activate-service-account --key-file gcloud-svcaccount-key.json
          - gcloud config set project ${GCLOUD_PROJECT}
