options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - export IMAGE_NAME=h0tbird/tva-voting:$BITBUCKET_COMMIT
          - docker build -t $IMAGE_NAME .
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - docker push $IMAGE_NAME
